services:
  - type: web
    name: g4-drivers-api
    env: docker
    plan: free
    region: oregon 
    buildCommand: docker build -t server .
    startCommand: ./server
    envVars:
      - key: PORT
        value: 8080
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_DB_HOST
        sync: false
      - key: SUPABASE_DB_PORT
        value: 5432
      - key: SUPABASE_DB_USER
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: SUPABASE_DB_NAME
        value: postgres
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
